responsiveness fix on right banner decor
acm-ucr/jm-products-website pull request #70
Opened 2024-07-24 16:23 UTC by aviamb

small screen: 
<img width="527" alt="image" src="https://github.com/user-attachments/assets/e0b42110-7c3b-4c06-923a-455434486c27">

medium screen:
<img width="525" alt="image" src="https://github.com/user-attachments/assets/3e0dd795-0c38-4af5-a002-baca8040fae3">

large screen: 
<img width="793" alt="image" src="https://github.com/user-attachments/assets/335b8bd5-fdd3-4c39-8b1f-036e8d9230ce">

fixes #63

2024-07-24 23:45 UTC, SafeDuck requested changes

2024-07-24 23:45 UTC, SafeDuck commented on src/components/Banner.jsx
> +      <div className="absolute w-1/6 -bottom-7 md:-bottom-10 lg:-bottom-20 right-0">
This is good, however can you also center the text

2024-07-27 05:43 UTC, aviamb commented
lg: 
<img width="815" alt="image" src="https://github.com/user-attachments/assets/8baf576c-5a79-41c0-91a6-47488ecece93">
 
md: 
<img width="542" alt="image" src="https://github.com/user-attachments/assets/6067fd49-4888-4b55-83f8-9c47ceb6a21f">

sm: 
<img width="558" alt="image" src="https://github.com/user-attachments/assets/702bda9d-31d4-47ae-a6e5-f32db2c0e6da">

2024-07-27 21:55 UTC, SafeDuck approved these changes

2024-07-27 21:55 UTC, merged