finished the bulk of it, just need to change formatting and colors of…
acm-ucr/jm-products-website pull request #74
Opened 2024-07-26 03:01 UTC by Ezkron

Heres what it looks like currently.

<img width="1246" alt="image" src="https://github.com/user-attachments/assets/6537c836-e60c-466f-a8e2-e94e1a45c493">

2024-07-26 03:13 UTC, Ezkron commented
Just need to fix the formatting in order to fit the image

2024-07-26 03:34 UTC, SafeDuck requested changes

2024-07-26 03:34 UTC, SafeDuck commented on src/components/about/WhoWeAre.jsx
> +    <div className="p-6">
use w-3/4.
use flex, flex-col, gap-10

2024-08-01 09:27 UTC, Ezkron commented
After making the changes, here is what it looks like now

<img width="1151" alt="image" src="https://github.com/user-attachments/assets/ef9ec8a7-4e31-4d74-bc91-6d3c33c3baca">

2024-08-02 03:07 UTC, SafeDuck requested changes

2024-08-02 03:07 UTC, SafeDuck commented on src/components/about/WhoWeAre.jsx
> +        <img
Use Image component from next.

2024-08-02 03:07 UTC, SafeDuck commented on src/components/about/WhoWeAre.jsx
> +          src="/images/about/JMbrochures.webp"
Statically import the image at the top, instead of putting the path directly inside the Image

2024-08-09 04:20 UTC, Ezkron commented
<img width="1112" alt="image" src="https://github.com/user-attachments/assets/1d289347-ab72-4e19-98d1-056ceaf21734">

2024-08-14 21:22 UTC, closed without merging