text banner complete
acm-ucr/jm-products-website pull request #75
Opened 2024-07-26 04:01 UTC by pjflipper1

2024-07-26 04:12 UTC, SafeDuck requested changes

2024-07-26 04:12 UTC, SafeDuck commented on src/components/clamps/LogoStrip.jsx
> +    <div className="flex justify-between p-4">
have width `w-1/2`

2024-07-26 04:12 UTC, SafeDuck commented on src/components/clamps/LogoStrip.jsx
> +        src="/images/lineclamps/companies/NASLogo.webp"
static import images at the top

2024-07-26 04:12 UTC, SafeDuck commented on src/components/clamps/LogoStrip.jsx
> +        width={180}
have width and height as taliwind utility classes

2024-08-02 03:24 UTC, pjflipper1 commented
![Uploading 352362590-3c0450ce-c0ba-4ef2-9d51-61c31d5e1302.png…]()

2024-08-02 03:27 UTC, pjflipper1 commented
![352362590-3c0450ce-c0ba-4ef2-9d51-61c31d5e1302](https://github.com/user-attachments/assets/a8e860f2-16e1-4f19-bdd3-c38b3e4ba7b0)

2024-08-02 04:24 UTC, closed without merging